//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGMSolutions.Students
{


    public partial class AssignmentsNew : global::System.Web.UI.Page
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertDiv;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Repeater rptAssignments;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl noAssignmentsDiv;
    }
}
